# Generated by Django 4.1.7 on 2023-03-04 19:47

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre_caja', models.CharField(max_length=50, verbose_name='Sucursal-Caja')),
                ('timbet', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Timbet')),
                ('betgana', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Betgana')),
                ('golden', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Golden')),
                ('soft', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Soft')),
                ('caballos_uh1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caballo UH1')),
                ('caballos_uh2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caballo UH2')),
                ('caballos_peruvian', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caballo Peruvian')),
                ('yapes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Yapes')),
                ('pos', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='POS')),
                ('pagos_tickets', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pago de Tickets')),
                ('gastos_generales', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Gastos Generales')),
                ('cobros_tickets', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cobro de Tickets')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Efectivo')),
                ('caja_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caja Anterior')),
                ('caja_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Caja Total')),
                ('total_sistemas', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Total en Sistemas')),
                ('egreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Egresos')),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ingresos')),
                ('total_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Total del Dia')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Diferencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
