# Generated by Django 4.1.3 on 2023-05-27 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sucursal', models.CharField(max_length=20, verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tinbet', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Timbet')),
                ('betgana', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Betgana')),
                ('golden', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Golden')),
                ('soft', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Soft')),
                ('caballos_uh1', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo UH1')),
                ('caballos_uh2', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo UH2')),
                ('caballos_peruvian', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo Peruvian')),
                ('mesa', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mesa')),
                ('yapes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Yapes')),
                ('pos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='POS')),
                ('pagos_tickets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pago de Tickets')),
                ('gastos_generales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gastos Generales')),
                ('cobros_tickets', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cobro de Tickets')),
                ('depositos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depositos')),
                ('recargas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Recargas')),
                ('ingreso_general', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos Generales')),
                ('efectivo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo')),
                ('caja_anterior', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja Anterior')),
                ('caja_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja Total')),
                ('total_sistemas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en Sistemas')),
                ('egreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Egresos')),
                ('ingreso_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos')),
                ('total_dia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total del Dia')),
                ('diferencia', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia')),
                ('calabaza', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Calabaza')),
                ('guardado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Guardado')),
                ('centimos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Centimos')),
                ('rotos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rotos')),
                ('virtuales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Virtuales')),
                ('cobre', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cobre')),
                ('cien', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='100')),
                ('cincuenta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='50')),
                ('veinte', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='20')),
                ('diez', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='10')),
                ('cinco', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='5')),
                ('dos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='2')),
                ('uno', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='1')),
                ('medio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='0.5')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('nombre_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
            },
        ),
    ]
