# Generated by Django 4.1.7 on 2023-03-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_rename_timbet_caja_tinbet_caja_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AddField(
            model_name='caja',
            name='calabaza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Calabaza'),
        ),
        migrations.AddField(
            model_name='caja',
            name='centimos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Centimos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='100'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cinco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='5'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cincuenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='50'),
        ),
        migrations.AddField(
            model_name='caja',
            name='cobre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Cobre'),
        ),
        migrations.AddField(
            model_name='caja',
            name='depositos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Depositos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='diez',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='10'),
        ),
        migrations.AddField(
            model_name='caja',
            name='dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='2'),
        ),
        migrations.AddField(
            model_name='caja',
            name='guardado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Guardado'),
        ),
        migrations.AddField(
            model_name='caja',
            name='ingreso_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ingresos Generales'),
        ),
        migrations.AddField(
            model_name='caja',
            name='medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='0.5'),
        ),
        migrations.AddField(
            model_name='caja',
            name='recargas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Recargas'),
        ),
        migrations.AddField(
            model_name='caja',
            name='rotos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Rotos'),
        ),
        migrations.AddField(
            model_name='caja',
            name='uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='1'),
        ),
        migrations.AddField(
            model_name='caja',
            name='veinte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='20'),
        ),
    ]
