# Generated by Django 4.1.7 on 2023-03-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0004_caja_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='betgana',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Betgana'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caballos_peruvian',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo Peruvian'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caballos_uh1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo UH1'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caballos_uh2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caballo UH2'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_anterior',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja Anterior'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='caja_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Caja Total'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='calabaza',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Calabaza'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='centimos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Centimos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cien',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='100'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cinco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='5'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cincuenta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='50'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cobre',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cobre'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cobros_tickets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cobro de Tickets'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='depositos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Depositos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='diez',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='10'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Diferencia'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='dos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='2'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='efectivo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Efectivo'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='egreso_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Egresos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='gastos_generales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gastos Generales'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='golden',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Golden'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='guardado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Guardado'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='ingreso_general',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos Generales'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='ingreso_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ingresos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='medio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='0.5'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='mesa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='pagos_tickets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pago de Tickets'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='pos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='POS'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='recargas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Recargas'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='rotos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Rotos'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='soft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Soft'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tinbet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Timbet'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_dia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total del Dia'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='total_sistemas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total en Sistemas'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='uno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='1'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='veinte',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='20'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='yapes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Yapes'),
        ),
    ]
