# Generated by Django 4.1.7 on 2023-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_alter_caja_betgana_alter_caja_caballos_peruvian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
