# Generated by Django 4.1.7 on 2023-03-14 15:28

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_alter_caja_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
