# Generated by Django 4.1.3 on 2023-03-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_alter_caja_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='virtuales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Virtuales'),
        ),
    ]
