# Generated by Django 4.1.3 on 2023-03-19 23:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_caja_virtuales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sucursal', models.CharField(max_length=20, verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.AlterField(
            model_name='caja',
            name='user',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='caja',
            name='nombre_caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caja.sucursales'),
        ),
    ]
