# Generated by Django 4.1.7 on 2023-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='fecha',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Fecha'),
        ),
    ]
