# Generated by Django 4.1.7 on 2023-03-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_alter_banco_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='fecha',
            field=models.DateField(unique=True, verbose_name='Fecha'),
        ),
    ]
