# Generated by Django 4.1.7 on 2023-03-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_banco_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposito',
            options={'verbose_name': 'Deposito', 'verbose_name_plural': 'Depositos'},
        ),
        migrations.AlterField(
            model_name='banco',
            name='fecha',
            field=models.DateField(auto_now_add=True, unique=True, verbose_name='Fecha'),
        ),
    ]
