# Generated by Django 4.1.7 on 2023-05-06 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_deposito_options_alter_banco_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={},
        ),
        migrations.RemoveField(
            model_name='banco',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='inicio',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='deposito',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='banco',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banco',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('pagos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.sucursal')),
            ],
            options={
                'verbose_name': 'Pagos',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
