# Generated by Django 4.1.7 on 2023-05-06 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_banco_options_remove_banco_disponible_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagos',
            new_name='Pago',
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RenameField(
            model_name='pago',
            old_name='pagos',
            new_name='pago',
        ),
    ]
