# Generated by Django 4.1.7 on 2023-05-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0006_rename_pagos_pago_alter_pago_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banco',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.RemoveField(
            model_name='banco',
            name='saldo_actual',
        ),
        migrations.AlterField(
            model_name='deposito',
            name='deposito',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pago',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
